version: '3.8'

services:
  controler:
    hostname: controler
    container_name: controler
    image: controler
    build: ${CONFIG}/controler
    command: ["sleep","infinity"]
    ports: 
     - ${CONTROLER_PORT_SSH}:22
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/controler/root:/root
    networks:
      btomka:
        ipv4_address: 10.5.0.4

  ubuntu:
    hostname: ubuntu
    container_name: ubuntu
    image: ubuntu-lab
    build: ${CONFIG}/ubuntu
    command: ["sleep","infinity"]
    ports: 
     - ${UBUNTU_PORT_SSH}:22
    privileged: true
    volumes:
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu1/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ubuntu1/root:/root
    networks:
      btomka:
        ipv4_address: 10.5.0.5

  centos:
    hostname: centos
    container_name: centos
    image: centos-lab
    build: ${CONFIG}/centos
    command: ["sleep","infinity"]
    ports: 
     - ${CENTOS_PORT_SSH}:22
    privileged: true
    volumes:
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos1/ansible:/home/ansible
     - ${ANSIBLE_HOME}/centos1/root:/root
    networks:
      btomka:
        ipv4_address: 10.5.0.6
     
networks:
  btomka:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1