version: '3.8'

services:
  ubuntu-c:
    hostname: ubuntu-c
    container_name: ubuntu-c
    image: ansible
    build: ./config/controler
    ports: 
     - ${UBUNTUC_PORT_SSHD}:22
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu-c/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ubuntu-c/root:/root
    networks:
     - btomka.io

  ubuntu1:
    hostname: ubuntu1
    container_name: ubuntu1
    image: ubuntu-lab
    build: ./config/ubuntu
    ports: 
     - ${UBUNTU1_PORT_SSHD}:22
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu1/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ubuntu1/root:/root
    networks:
     - btomka.io

  ubuntu2:
    hostname: ubuntu2
    container_name: ubuntu2
    image: ubuntu-lab
    build: ./config/ubuntu
    ports: 
     - ${UBUNTU2_PORT_SSHD}:22
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu2/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ubuntu2/root:/root
    networks:
     - btomka.io

  ubuntu3:
    hostname: ubuntu3
    container_name: ubuntu3
    image: ubuntu-lab
    build: ./config/ubuntu
    ports: 
     - ${UBUNTU3_PORT_SSHD}:22
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu3/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ubuntu3/root:/root
    networks:
     - btomka.io

  centos1:
    hostname: centos1
    container_name: centos1
    image: centos-lab
    build: ./config/centos
    ports: 
     - ${CENTOS1_PORT_SSHD}:22
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos1/ansible:/home/ansible
     - ${ANSIBLE_HOME}/centos1/root:/root
    networks:
     - btomka.io

  centos2:
    hostname: centos2
    container_name: centos2
    image: centos-lab
    build: ./config/centos
    ports: 
     - ${CENTOS2_PORT_SSHD}:22
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos2/ansible:/home/ansible
     - ${ANSIBLE_HOME}/centos2/root:/root
    networks:
     - btomka.io

  centos3:
    hostname: centos3
    container_name: centos3
    image: centos-lab
    build: ./config/centos
    ports: 
     - ${CENTOS3_PORT_SSHD}:22
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos3/ansible:/home/ansible
     - ${ANSIBLE_HOME}/centos3/root:/root
    networks:
     - btomka.io

networks:
  btomka.io:
    name: btomka.io