version: '3.8'

services:
  pik:
    hostname: pik
    container_name: pik
    image: pik
    build: ${CONFIG}/pik
    command: ["/usr/sbin/sshd","-D"]
    ports: 
     - ${PIK_SSH_PORT}:22
    privileged: true
    volumes:
      # TODO add ssh pub key
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/pik/root:/root
    networks:
      btomka:
        ipv4_address: 10.5.0.2

  tref:
    hostname: tref
    container_name: tref
    image: tref
    build: ${CONFIG}/tref
    command: ["/usr/sbin/sshd","-D"]
    ports: 
     - ${TREF_SSH_PORT}:22
    privileged: true
    volumes:
      # TODO add ssh pub key
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/tref/root:/root
    networks:
      btomka:
        ipv4_address: 10.5.0.3
     
networks:
  btomka:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
