version: '3.8'

services:
  pik:
    hostname: pik
    container_name: pik
    image: pik
    build: ${CONFIG}/pik
    command: ["/usr/sbin/sshd","-D"]
    ports: 
     - ${CONTROLER_PORT_SSH}:22
    privileged: true
    volumes:
      # TODO add ssh pub key
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/pik/root:/root
    networks:
      btomka:
        ipv4_address: 10.5.0.2

  herc:
    hostname: herc
    container_name: herc
    image: herc
    build: ${CONFIG}/herc
    command: ["/usr/sbin/sshd","-D"]
    ports: 
     - ${UBUNTU_PORT_SSH}:22
    privileged: true
    volumes:
      # TODO add ssh pub key
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/herc/root:/root
    networks:
      btomka:
        ipv4_address: 10.5.0.3

  tref:
    hostname: tref
    container_name: tref
    image: tref
    build: ${CONFIG}/tref
    command: ["/usr/sbin/sshd","-D"]
    ports: 
     - ${CENTOS_PORT_SSH}:22
    privileged: true
    volumes:
      # TODO add ssh pub key
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/tref/root:/root
    networks:
      btomka:
        ipv4_address: 10.5.0.4
     
networks:
  btomka:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
