version: '3.8'

services:
  controler:
    hostname: pik
    container_name: pik
    image: pik
    build: ${CONFIG}/pik
    command: ["/usr/sbin/sshd","-D"]
    ports: 
     - ${CONTROLER_PORT_SSH}:22
    privileged: true
    volumes:
      # TODO add ssh pub key
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/pik/root:/root
    networks:
      btomka:
        ipv4_address: 10.5.0.2

  ubuntu:
    hostname: ubuntu
    container_name: ubuntu
    image: bubuntu
    build: ${CONFIG}/ubuntu
    command: ["/usr/sbin/sshd","-D"]
    ports: 
     - ${UBUNTU_PORT_SSH}:22
    privileged: true
    volumes:
      # TODO add ssh pub key
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu/root:/root
    networks:
      btomka:
        ipv4_address: 10.5.0.3

  centos:
    hostname: centos
    container_name: centos
    image: bcentos
    build: ${CONFIG}/centos
    command: ["/usr/sbin/sshd","-D"]
    ports: 
     - ${CENTOS_PORT_SSH}:22
    privileged: true
    volumes:
      # TODO add ssh pub key
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos/root:/root
    networks:
      btomka:
        ipv4_address: 10.5.0.4
     
networks:
  btomka:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
