# This is a basic workflow that is manually triggered

name: Deploy Ubuntu
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Deploy Ubuntu on KVM'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  run-playbooks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Set up Python 3.
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Ansible.
      run: pip3 install ansible-core

    - name: Show services
      shell: bash
      run: |
        ansible --version
        python --version

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: playbook.yml
        # Optional, directory where playbooks live
        directory: ./
        # Optional, ansible configuration file content (ansible.cfg)
        configuration: ansible.cfg
        # Optional, SSH private key
        key: ${{secrets.SSH_PRIVATE_KEY}}
        # Optional, literal inventory file contents
        inventory: hosts
        # Optional, SSH known hosts file content
        known_hosts: my_ssh_key
        # Optional, encrypted vault password
        vault_password: ${{secrets.VAULT_PASSWORD}}
      
