# This is a basic workflow to help you get started with Actions

name: Setup VM

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ipadd:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Input IP address of the VM'
        # Default value if no value is explicitly provided
        default: '0.0.0.0'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup_vm:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run Ansible playbook
        shell: bash
        run: |
          cd ./docker_installation_kvm/
          chmod 600 my_ssh_key
          sed 's/ubuntu-terraform/${{ inputs.ipadd }}/g' hosts
          ansible-playbook playbook.yml
